### PR TITLE
Use ayatanamenuitemfactory.(c|h) from ayatana-ido. Reduce code duplic…

### PR DESCRIPTION
**Pull request by sunweaver**
…ations.

Depends on AyatanaIndicators/ayatana-ido#13.

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01: OMG!!! This was really a blind shot, more of a cleanup. But the freezes seem to be gone with this PR applied (and ayatana-ido#13).

**Comment by sunweaver** [comment]
... IDO widgets get rendered on Ubuntu and Debian alike...

**Comment by sunweaver** [comment]
... I will now dump my Ubuntu MATE VM, reinstall, reapply patches, test-build and verify that this really works!

**Comment by tari01** [comment]
Yay! I've built, installed, tested both - works fine on my end. I don't care if it was luck or persistence: Great work!

Want a funny story to go with it? It was I who broke this when I fixed the IDOs and duplicated the code. There, I said it (stones flying/me ducks).

Now it makes perfect sense: the recursion I was talking about earlier - Ubuntu was trying to register the menu item factory from both sources.

And finally, a stupid (rhetorical) question: why on earth would this work anywhere but Ubuntu? WHY?

Merged, ready to push, give me the word.

**Comment by sunweaver** [comment]
> Yay! I've built, installed, tested both - works fine on my end. I don't care if it was luck or persistence: Great work!

Grrrr... with the rebuilt Ubuntu MATE VM I get another issue now. The mouse events are not processed at all anymore. Neither in the greeter, nor in the MATE session.

> Want a funny story to go with it? It was I who broke this when I fixed the IDOs and duplicated the code. There, I said it (stones flying/me ducks).

Don't worry.

> Now it makes perfect sense: the recursion I was talking about earlier - Ubuntu was trying to register the menu item factory from both sources.

Yeah, that lead me to the PRs.

> And finally, a stupid (rhetorical) question: why on earth would this work anywhere but Ubuntu? WHY?

Dunno! Really. I will rebuild GTK-3, as well and disable that one patch once more and see if the mouse events are then processed ok. But maybe it is a VM issue? I will install another LightDM greeter to check that.

> Merged, ready to push, give me the word.

Please push anyway. The freezes are gone, it is just something weird with the event processing now.

**Comment by sunweaver** [comment]
I have a sense that the VM is somehow defunct (regarding the mouse events...).

**Comment by sunweaver** [comment]
Ok, it was the VM. It all seems to work very well now!

@tari01: can you look at the mal-positioning of menus, icons related to the indicator icons now? You said that it will be simple!?!

**Comment by tari01** [comment]
> @tari01: can you look at the mal-positioning of menus, icons related to the indicator icons now? You said that it will be simple!?!

It will be. Can you please give me the name of the theme your greeter uses, I will need that for reference when testing the padding. I'll now go horizontal, to be continued tomorrow.

**Comment by sunweaver** [comment]
> > @tari01: can you look at the mal-positioning of menus, icons related to the indicator icons now? You said that it will be simple!?!
> 
> It will be. Can you please give me the name of the theme your greeter uses, I will need that for reference when testing the padding. I'll now go horizontal, to be continued tomorrow.

@tari01: the Arctica Greeter uses the numix-theme and numix-icon-theme by default.

**Comment by sunweaver** [comment]
Let's move the menu positioning discussion over to #17. Thanks.

**Pull request merged**
